FORMAT: 1A
HOST: http://openpizza.herokuapp.com/

# OpenPizza
OpenPizza is a service which allows to order pizzas and other meals from your favorite home delivery service via open API.

# Group Shops

## Shop Collection [/shops{?postcode}]
### List all Shops [GET]

+ Parameters
    + postcode (optional, string) ... Search for shops with postcode

+ Response 200 (application/json)

        [{
            "id": 1,
            "name": "Christophs Pizza",
            "address": "Karlstrasse 123",
            "postcode": "67676",
            "city": "Karlsruhe"
        },
        {
            "id": 1,
            "name": "Freddies Pizza",
            "address": "Karlstrasse 123",
            "postcode": "67676",
            "city": "Karlsruhe"
        }
        ,{
            "id": 1,
            "name": "Patricks Pizza",
            "address": "Karlstrasse 123",
            "postcode": "67676",
            "city": "Karlsruhe"
        },
        {
            "id": 1,
            "name": "Jannis' Pizza",
            "address": "Karlstrasse 123",
            "postcode": "67676",
            "city": "Karlsruhe"
        },
        {
            "id": 1,
            "name": "Florians Pizza",
            "address": "Karlstrasse 123",
            "postcode": "67676",
            "city": "Karlsruhe"
        }]

## Shop [/shops/{id}]
A single Shop object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with.

### Retrieve a Shop [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Christophs Pizza",
            "address": "Karlstrasse 123",
            "postcode": "67676",
            "city": "Karlsruhe",
            "product_categories": [
                "Pizza",
                "Pasta"
            ],
            "products": [
                {
                    "id": 1,
                    "name": "Pizza Diablo",
                    "category": "Pizza",
                    "price": 8.45
                },{
                    "id": 1,
                    "name": "Pizza Margherita",
                    "category": "Pizza",
                    "price": 8.45
                },{
                    "id": 1,
                    "name": "Pizza Gorgonzola",
                    "category": "Pizza",
                    "price": 8.45
                },
                {
                    "id": 2,
                    "name": "Pasta Bolognese",
                    "category": "Pasta",
                    "price": 5.10
                },
                {
                    "id": 2,
                    "name": "Pasta Pesto",
                    "category": "Pasta",
                    "price": 5.10
                },
                {
                    "id": 2,
                    "name": "Pasta Tomato",
                    "category": "Pasta",
                    "price": 5.10
                },
                {
                    "id": 2,
                    "name": "Pasta Al Dente",
                    "category": "Pasta",
                    "price": 5.10
                }
            ]
        }

# Group Orders

## Order Collection [/orders/]

### Create a order [POST]
Start a new order. This action requries an authorized user. The response the full order.

+ Request (application/json)

            {
                "estimated_participants": 6,
                "shop": 1,
                "delivery_address": {
                    "name": "Max Pizzahunger",
                    "address": "Karlstrasse 123",
                    "postcode": "67676",
                    "city": "Karlsruhe"
                },
                "comment": "Sliced please."
            }

+ Response 201 (application/json)

            {
                "id": "2d931510-d99f-494a-8c67-87feb05e1594",
                "short_link": "http://open-pizza.de/2d931510-d99f-494a-8c67-87feb05e1594",
                "host": "Paul Power",
                "estimated_participants": 6,
                "shop": 1,
                "delivery_address": {
                    "name": "Max Pizzahunger",
                    "address": "Karlstrasse 123",
                    "postcode": "67676",
                    "city": "Karlsruhe"
                }
            }

## Order [/orders/{id}]
Single order object which includes basic informations about a order. Detail informations about ordered products can you find under ``/orders/{id}/items``.

- ``short_link`` Link to page which opens the app or allows to add itmes to order via web app.
- ``shop`` Shop id.
- ``host`` Name of user which hosts and manages this order.
- ``estimated_participants`` How many people will be order something?

+ Parameters
    + id (required, uuid4, `62936e70-1815-439b-bf89-8492855a7e6b`) ... Unique id for a order. 
    
### Get active order [GET]

+ Response 200
    
            {
                "id": "2d931510-d99f-494a-8c67-87feb05e1594",
                "short_link": "http://open-pizza.de/2d931510-d99f-494a-8c67-87feb05e1594",
                "host": "Paul Power",
                "shop": 1,
                "estimated_participants": 6,
                "delivery_address": {
                    "name": "Max Pizzahunger",
                    "address": "Karlstrasse 123",
                    "postcode": "67676",
                    "city": "Karlsruhe"
                }
            }

## Order Content [/orders/{id}/items]

+ Parameters
    + id (required, uuid4, `62936e70-1815-439b-bf89-8492855a7e6b`) ... Unique id for a order. 
 
### Get all current items of order [GET]

+ Response 200
    
    + body
    
            [{
                "nickname": "frederic",
                "products": [
                    {
                        "id": 123,
                        "name": "Pizza Diablo",
                        "quantity": 3
                    }
                ],
                "comment": "Not too much olive oil.",
                "price": 12.88
            },{
                "nickname": "florian",
                "products": [
                    {
                        "id": 123,
                        "name": "Pizza Margherita",
                        "quantity": 3
                    }
                ],
                "comment": "Not too much olive oil.",
                "price": 12.88
            }]

## Order Content for nickname [/orders/{id}/items/{nickname}]

+ Parameters
    + nickname (required, string, `frederic`) ... Unique nickname per order. 

### Add item to order for nickname [POST]

If the nickname for this order is already taken than the API will return status code ``409 CONFLICT``. The user must use another nickname.

``note`` can be empty.

+ Request

        {
            "nicknames": "frederic",
            "products": [
                {
                    "id": 123,
                    "quantity": 3
                }
            ],
            "comment": "Not too much olive oil."
        }

+ Response 201

        {
            "products": [
                {
                    "id": 123,
                    "name": "Pizza Diablo",
                    "quantity": 3
                }
            ],
            "comment": "Not too much olive oil."
            "price": 12.88
        }

+ Response 409
    
        {
            "message": "Nickname already ordered"
        }

